### ISSUE TITLE
dependency issues 

### ISSUE THREAD

**Issue by SDcodehub** [IMJONEZZ/LLMs-in-Production#1]
trying to install the requirements.txt, facing lot of dependency issues.

will it be possible to create an updated requirements.txt as these packages have evolved a lot, and current set have lot of dependency issues, between openai, langchain, gardio, langkit[all]

using `pyenv` with `python 3.11.2`

**Comment by SDcodehub** [comment]
pydentic is causing lot of issues, tried few version to experiment

```
The conflict is caused by:
    gradio 4.8.0 depends on pydantic>=2.0
    langchain 0.1.0 depends on pydantic<3 and >=1
    ray[default] 2.5.1 depends on pydantic; extra == "default"
    fastapi 0.89.1 depends on pydantic!=1.7, !=1.7.1, !=1.7.2, !=1.7.3, !=1.8, !=1.8.1, <2.0.0 and >=1.6.2
    gradio 4.8.0 depends on pydantic>=2.0
    langchain 0.1.0 depends on pydantic<3 and >=1
    ray[default] 2.5.1 depends on pydantic; extra == "default"
    fastapi 0.88.0 depends on pydantic!=1.7, !=1.7.1, !=1.7.2, !=1.7.3, !=1.8, !=1.8.1, <2.0.0 and >=1.6.2
```

**Comment by IMJONEZZ** [comment]
Yeah homie, we made the decision to finish writing all of the projects,
then we’ll update the requirements.txt along with some other helpful
package management so it’s nice for you to run.

My book: LLMs in Production
45% discount - https://shortener.manning.com/amDJ


Dňa ne 28. 1. 2024 o 6:46 Sagar Desai ***@***.***>
napísala(a):

**Comment by SDcodehub** [comment]
Already purchased book, great collection,

sounds good, I will wait try out till then.
